### ISSUE TITLE
Crash when playing Station from Browsed Radio in 18.x

### ISSUE THREAD

**Issue by abbaskip** [vially/googlemusic-xbmc#107]
I'm running Leia, and two issues I've noticed. First "I'm Feeling Lucky Mix" populates with no songs.

Secondly, if I browse radios and select a radio to play, Kodi crashes.

If I browse my library, or search for songs to play etc, it works fine. I can even start radio from a song. I just can't browse radios stations.

**Comment by foreverguest** [comment]
I have a test version available, please check if the problems are present with it too.

Download link: https://app.box.com/s/m3wxz9rk9jnj123ohgeouu9kn8w3e2fa

**Comment by abbaskip** [comment]
Hey mate, this fixes the I'm Feeling Lucky issue, but not the Radio one.

**Comment by foreverguest** [comment]
Fixed.
