### ISSUE TITLE
Script error using latest 0.8 with Fordo for Windows

### ISSUE THREAD

**Issue by pro2k** [vially/googlemusic-xbmc#19]
21:54:01 T:2764  NOTICE: -->Python Interpreter Initialized<--
21:54:01 T:2764  NOTICE: GoogleMusic-0.8.0 ARGV: ['plugin://plugin.audio.googlemusic/', '1', '']
21:54:02 T:2764   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named unittest2
                                            Traceback (most recent call last):
                                              File "C:\Users\Pedro Solorzano\AppData\Roaming\XBMC\addons\plugin.audio.googlemusic\default.py", line 43, in <module>
                                                import GoogleMusicApi
                                              File "C:\Users\Pedro Solorzano\AppData\Roaming\XBMC\addons\plugin.audio.googlemusic\GoogleMusicApi.py", line 3, in <module>
                                                from gmusicapi.api import Api
                                              File "C:\Users\Pedro Solorzano\AppData\Roaming\XBMC\addons\script.module.gmusicapi\lib\gmusicapi__init__.py", line 10, in <module>
                                                from gmusicapi.api import Api
                                              File "C:\Users\Pedro Solorzano\AppData\Roaming\XBMC\addons\script.module.gmusicapi\lib\gmusicapi\api.py", line 17, in <module>
                                                from gmusicapi.gmtools import tools
                                              File "C:\Users\Pedro Solorzano\AppData\Roaming\XBMC\addons\script.module.gmusicapi\lib\gmusicapi\gmtools\tools.py", line 10, in <module>
                                                from gmusicapi.compat import Counter
                                              File "C:\Users\Pedro Solorzano\AppData\Roaming\XBMC\addons\script.module.gmusicapi\lib\gmusicapi\compat.py", line 14, in <module>
                                                import unittest2 as unittest
                                            ImportError: No module named unittest2
                                            -->End of Python script error report<--
21:54:02 T:2508   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.audio.googlemusic
21:54:02 T:2508   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.audio.googlemusic) failed
21:54:08 T:2508  NOTICE: Storing total System Uptime
21:54:08 T:2508  NOTICE: Saving settings
21:54:08 T:2508  NOTICE: stop all
21:54:08 T:2508  NOTICE: ES: Stopping event server
21:54:09 T:2220  NOTICE: ES: UDP Event server stopped
21:54:09 T:2508  NOTICE: stopping zeroconf publishing
21:54:09 T:2508  NOTICE: Webserver: Stopping...
21:54:09 T:2508  NOTICE: WebServer: Stopped the webserver
21:54:09 T:2508  NOTICE: Webserver: Stopped...
21:54:09 T:2508  NOTICE: stop sap announcement listener
21:54:09 T:2508  NOTICE: clean cached files!
21:54:09 T:2508  NOTICE: unload skin
21:54:09 T:5736  NOTICE: StorageServer-2.5.0 Closed down
21:54:09 T:2508  NOTICE: stop python
21:54:09 T:2508  NOTICE: stopped
21:54:09 T:2508  NOTICE: destroy
21:54:09 T:2508  NOTICE: closing down remote control service
21:54:09 T:2508  NOTICE: unload sections
21:54:09 T:2508  NOTICE: destroy
21:54:09 T:2508 WARNING: Attempted to remove window 10013 from the window manager when it didn't exist
21:54:09 T:2508 WARNING: Attempted to remove window 10014 from the window manager when it didn't exist
21:54:09 T:2508 WARNING: Attempted to remove window 10015 from the window manager when it didn't exist
21:54:09 T:2508 WARNING: Attempted to remove window 10016 from the window manager when it didn't exist
21:54:09 T:2508 WARNING: Attempted to remove window 10017 from the window manager when it didn't exist
21:54:09 T:2508 WARNING: Attempted to remove window 10018 from the window manager when it didn't exist
21:54:09 T:2508 WARNING: Attempted to remove window 10019 from the window manager when it didn't exist
21:54:09 T:2508 WARNING: Attempted to remove window 10021 from the window manager when it didn't exist
21:54:09 T:2508 WARNING: Attempted to remove window 10107 from the window manager when it didn't exist
21:54:09 T:2508 WARNING: Attempted to remove window 10115 from the window manager when it didn't exist
21:54:09 T:2508 WARNING: Attempted to remove window 10104 from the window manager when it didn't exist
21:54:09 T:2508  NOTICE: closing down remote control service
21:54:09 T:2508  NOTICE: unload sections
21:54:09 T:2508  NOTICE: application stopped...

**Comment by vially** [comment]
I'll fix this properly in the next version but until then a quickfix would be to remove (or comment) line 14: `import unittest2 as unittest` in ADDON_DIR/script.module.gmusicapi/lib/gmusicapi/compat.py

**Comment by pro2k** [comment]
Thank for your help!

Here is the new log.

22:11:48 T:2784  NOTICE: GoogleMusic-0.8.0 ARGV: ['plugin://plugin.audio.googlemusic/', '1', '']
22:11:50 T:2784   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named dateutil.parser
                                            Traceback (most recent call last):
                                              File "C:\Users\Pedro Solorzano\AppData\Roaming\XBMC\addons\plugin.audio.googlemusic\default.py", line 43, in <module>
                                                import GoogleMusicApi
                                              File "C:\Users\Pedro Solorzano\AppData\Roaming\XBMC\addons\plugin.audio.googlemusic\GoogleMusicApi.py", line 3, in <module>
                                                from gmusicapi.api import Api
                                              File "C:\Users\Pedro Solorzano\AppData\Roaming\XBMC\addons\script.module.gmusicapi\lib\gmusicapi__init__.py", line 10, in <module>
                                                from gmusicapi.api import Api
                                              File "C:\Users\Pedro Solorzano\AppData\Roaming\XBMC\addons\script.module.gmusicapi\lib\gmusicapi\api.py", line 22, in <module>
                                                from gmusicapi.protocol import webclient, musicmanager, upload_pb2, locker_pb2
                                              File "C:\Users\Pedro Solorzano\AppData\Roaming\XBMC\addons\script.module.gmusicapi\lib\gmusicapi\protocol\musicmanager.py", line 11, in <module>
                                                import dateutil.parser
                                            ImportError: No module named dateutil.parser
                                            -->End of Python script error report<--
22:11:50 T:3932   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.audio.googlemusic
22:11:50 T:3932   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.audio.googlemusic) failed

**Comment by vially** [comment]
It seems that I should have done some more testing before releasing this version.
Until I release the next version can you try again with this version of [gmusicapi](https://docs.google.com/uc?export=download&id=0B3hilBJzOZ-1LTdSNi1Gc294SWc)

You might have to manually remove the old version from ADDON_DIR/plugin.script.gmusicapi before installing this version since it has the exact version number.

Sorry about the trouble but I want to make sure it works properly this time before I make another release.

EDIT: I've updated the forum [post](http://forum.xbmc.org/showthread.php?tid=134783&pid=1351142#pid1351142) with gmusicapi version 2013.02.28 which should include these two fixes.

**Comment by pro2k** [comment]
Now is working with google music account that only has almost 50 songs, no playlist, no special settings. on the other hand with another account that has ~2500, playlist, etc is not working.

 19:05:34 T:272  NOTICE: GoogleMusic-0.8.1 ARGV: ['plugin://plugin.audio.googlemusic/', '8', '']
19:05:37 T:272  NOTICE: CommonFunctions-2.5.1
19:05:37 T:272  NOTICE: [GoogleMusic-0.8.1] Logging in
19:05:41 T:272  NOTICE: [GoogleMusic-0.8.1] Login succeeded
19:06:00 T:272   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: ('url',)
                                            Traceback (most recent call last):
                                              File "C:\Users\Pedro Solorzano\AppData\Roaming\XBMC\addons\plugin.audio.googlemusic\default.py", line 67, in <module>
                                                navigation.api.updatePlaylistSongs('all_songs')
                                              File "C:\Users\Pedro Solorzano\AppData\Roaming\XBMC\addons\plugin.audio.googlemusic\GoogleMusicApi.py", line 58, in updatePlaylistSongs
                                                self.storage.storeApiSongs(api_songs, playlist_id)
                                              File "C:\Users\Pedro Solorzano\AppData\Roaming\XBMC\addons\plugin.audio.googlemusic\GoogleMusicStorage.py", line 157, in storeApiSongs
                                                ":url, :total_discs, :duration_millis, :album_art_url, :display_name, NULL)", songs())
                                              File "C:\Users\Pedro Solorzano\AppData\Roaming\XBMC\addons\plugin.audio.googlemusic\GoogleMusicStorage.py", line 147, in songs
                                                'url': api_song["url"],
                                            KeyError: ('url',)
                                            -->End of Python script error report<--
19:06:00 T:4424   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.audio.googlemusic/
19:06:00 T:4424   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.audio.googlemusic/) failed
19:06:00 T:2772  NOTICE: Thread Background Loader start, auto delete: false
19:11:35 T:4424  NOTICE: Previous line repeats 1 times.
19:11:35 T:4424  NOTICE: Storing total System Uptime
19:11:35 T:4424  NOTICE: Saving settings
19:11:35 T:4424  NOTICE: stop all
19:11:35 T:4424  NOTICE: ES: Stopping event server
19:11:36 T:4108  NOTICE: ES: UDP Event server stopped
19:11:36 T:4424  NOTICE: stopping zeroconf publishing
19:11:36 T:4424  NOTICE: Webserver: Stopping...
19:11:36 T:4424  NOTICE: WebServer: Stopped the webserver
19:11:36 T:4424  NOTICE: Webserver: Stopped...
19:11:36 T:4424  NOTICE: stop sap announcement listener
19:11:36 T:4424  NOTICE: clean cached files!
19:11:36 T:4424  NOTICE: unload skin
19:11:36 T:4424 WARNING: CGUITextureManager::Cleanup: Having to cleanup texture button-focus.png
19:11:36 T:4424 WARNING: CGUITextureManager::Cleanup: Having to cleanup texture button-nofocus.png
19:11:36 T:4340  NOTICE: StorageServer-2.5.0 Closed down
19:11:36 T:4424  NOTICE: stop python
19:11:36 T:4424  NOTICE: stopped
19:11:36 T:4424  NOTICE: destroy
19:11:36 T:4424  NOTICE: closing down remote control service
19:11:36 T:4424  NOTICE: unload sections
19:11:37 T:4424  NOTICE: destroy
19:11:37 T:4424 WARNING: Attempted to remove window 10013 from the window manager when it didn't exist
19:11:37 T:4424 WARNING: Attempted to remove window 10014 from the window manager when it didn't exist
19:11:37 T:4424 WARNING: Attempted to remove window 10015 from the window manager when it didn't exist
19:11:37 T:4424 WARNING: Attempted to remove window 10016 from the window manager when it didn't exist
19:11:37 T:4424 WARNING: Attempted to remove window 10017 from the window manager when it didn't exist
19:11:37 T:4424 WARNING: Attempted to remove window 10018 from the window manager when it didn't exist
19:11:37 T:4424 WARNING: Attempted to remove window 10019 from the window manager when it didn't exist
19:11:37 T:4424 WARNING: Attempted to remove window 10021 from the window manager when it didn't exist
19:11:37 T:4424 WARNING: Attempted to remove window 10107 from the window manager when it didn't exist
19:11:37 T:4424 WARNING: Attempted to remove window 10115 from the window manager when it didn't exist
19:11:37 T:4424 WARNING: Attempted to remove window 10104 from the window manager when it didn't exist
19:11:37 T:4424  NOTICE: closing down remote control service
19:11:37 T:4424  NOTICE: unload sections
19:11:37 T:4424  NOTICE: application stopped...

**Comment by vially** [comment]
Try this version: [0.8.2](https://docs.google.com/file/d/0B3hilBJzOZ-1TDd2aEx3elJ6WGM/edit)

**Comment by pro2k** [comment]
Nice, seems that all works as it should be.

**Comment by vially** [comment]
Great. In that case I'm closing the issue for now.
