### ISSUE TITLE
Plugin needs administrator permissions to run on Windows 7

### ISSUE THREAD

**Issue by rpj2004** [vially/googlemusic-xbmc#2]
The plugin right now requires administrator permissions to run on Windows 7.  This is because it tries to write the log file (googlemusicapi.log or something I think) in the Program Files/XBMC directory.

I fixed this on my computer by changing apilogging.py to create the log file in the special://profile/addon_data/ directory instead, but a real fix is needed.

Thanks.

**Comment by robweber** [comment]
Just found this as well. Was going to create a new issue for it but thought I'd write it up in here first. I did a similar fix importing the xbmc python library and translating the path to special://profile/addon_data/script_name. Probably a good idea to fix this even for non windows machines as addons shouldn't write data to the root xbmc install directory. 

I'd be happy to throw a patch together if needed.

**Comment by vially** [comment]
Fixed in latest version
