### ISSUE TITLE
dependencies not met on raspbmc install

### ISSUE THREAD

**Issue by tenaran** [vially/googlemusic-xbmc#20]
Sorry if this is a really obvious question, not done this before - I've just "installed from zip file" on my raspbmc device and got the brief error "dependencies not met". How do I find out more? Does anyone know what dependencies and where I can get them?

**Comment by hettinger77** [comment]
install the dependencies mentioned on this thread by the author:

http://forum.xbmc.org/showthread.php?tid=134783
