### ISSUE TITLE
Failed to Retrieve Items from a newly created playlist

### ISSUE THREAD

**Issue by anshul10s** [vially/googlemusic-xbmc#3]
Hi Vially,
  First of all thanks for creating such a wonderful plugin, I really like it :) 

I wanted to report an issue. I recently created a new Playlist "Recent", its showing up in my PlayList but when I am fetching content of this playlist, I am getting following errors

18:42:39 T:2699029312   ERROR: 2012-09-08 18:42:39,219 - gmusicapi.Api - ERROR - call to loadplaylist failed
18:42:39 T:2699029312  NOTICE: .
18:42:39 T:2699029312   ERROR: Error Type: <class 'gmusicapi.api.CallFailure'>
18:42:39 T:2699029312   ERROR: Error Contents: api call get_playlist_songs failed; server returned {u'reloadXsrf': True, u'success': False}
18:42:39 T:2699029312   ERROR: Traceback (most recent call last):
                                              File "/home/anshul3/.xbmc/addons/plugin.audio.googlemusic/default.py", line 45, in <module>
                                                navigation.listMenu(params)
                                              File "/home/anshul3/.xbmc/addons/plugin.audio.googlemusic/GoogleMusicNavigation.py", line 42, in listMenu
                                                self.listPlaylistSongs(get("playlist_id"))
                                              File "/home/anshul3/.xbmc/addons/plugin.audio.googlemusic/GoogleMusicNavigation.py", line 101, in listPlaylistSongs
                                                songs = self.api.getPlaylistSongs(playlist_id)
                                              File "/home/anshul3/.xbmc/addons/plugin.audio.googlemusic/GoogleMusicApi.py", line 22, in getPlaylistSongs
                                                self.updatePlaylistSongs(playlist_id)
                                              File "/home/anshul3/.xbmc/addons/plugin.audio.googlemusic/GoogleMusicApi.py", line 49, in updatePlaylistSongs
                                                api_songs = self.gmusicapi.get_playlist_songs(playlist_id)
                                              File "/home/anshul3/.xbmc/addons/script.module.gmusicapi/lib/gmusicapi/api.py", line 288, in get_playlist_songs
                                                return self._wc_call("loadplaylist", playlist_id)["playlist"]
                                              File "/home/anshul3/.xbmc/addons/script.module.gmusicapi/lib/gmusicapi/api.py", line 639, in _wc_call
                                                raise CallFailure(calling_func_name, res) #normally caused by bad arguments to the server
                                            CallFailure: api call get_playlist_songs failed; server returned {u'reloadXsrf': True, u'success': False}
18:42:39 T:3019536128   ERROR: GetDirectory - Error getting plugin://plugin.audio.googlemusic/?path=playlist&playlist_id=c301d029-87a4-492b-96d5-3da82373eb29
18:42:39 T:3019536128   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.audio.googlemusic/?path=playlist&playlist_id=c301d029-87a4-492b-96d5-3da82373eb29) failed
18:42:39 T:2666519360  NOTICE: -->Python Interpreter Initialized<--
18:42:39 T:2666519360  NOTICE: GoogleMusic-0.2.1 ARGV: ['plugin://plugin.audio.googlemusic/', '0', '?path=playlists&playlist_type=user']
18:42:39 T:2666519360  NOTICE: CommonFunctions-1.1.0
18:42:39 T:2666519360  NOTICE: [GoogleMusic-0.2.1] getPlaylists : 'Getting playlists of type: user'
18:42:39 T:2666519360  NOTICE: [GoogleMusic-0.2.1] getPlaylists : '[(u'829e7c27-84de-493b-a017-ce29c4673ed6', u'Like ', u'user', 1), (u'0a92b38a-fcb8-3099-887c-073ccaf62f06', u'dance', u'user', 1), (u'758d45d2-231b-3b91-abd3-ba9f53ee389e', u'midomi', u'user', 1), (u'9617decd-a96a-4fb6-be49-767264b6917e', u'MISS YOU Mix', u'user', 1), (u'f826313e-2323-4986-9f16-03e2d9588e08', u'Fav', u'user', 1), (u'24eabcb4-3426-3cb4-bbf4-2227a3771bb0', u'Pop Archived', u'user', 0), (u'f2e708c4-5a51-3a1e-9212-4685f6a4c4d3', u'Genius', u'user', 0), (u'a6f377cc-f947-3e47-be7d-7f6d150ded42', u'fast no', u'user', 1), (u'b1716f1b-e6f3-333a-9d16-49ea12520b01', u'bhat songs', u'user', 0), (u'625b82ff-f833-3819-9dc7-8d320f352ce8', u'tapping', u'user', 1), (u'82456739-64ab-3a66-8b0d-c70b80a78f76', u'slow romantic', u'user', 1), (u'c301d029-87a4-492b-96d5-3da82373eb29', u'Recent', u'user', 0)]'

I initially thought it may be the cookie issue, so cleared that also and tried, but not success. Let me know if I can help you with any other info.

Anshul

**Comment by vially** [comment]
Hi Anshul,

Thanks for the feedback. From what I see from the log it seems to be an issue with the Google Music Unofficial API. This plugin uses a slightly outdated version of the Google-Music-Unofficial-API. Maybe if you try to update to the latest version of the API you might be able to make it work again.

I would try to fix it myself but right now I'm a little busy with some personal projects. Hopefully, once I'll find some free time I'm planning to release a new version of this plugin to deal with all these issues that have accumulated.

Cheers!

**Comment by anshul10s** [comment]
Thanks Valentine, let me see if I can upgrade it.

Anshul

**Comment by ghost** [comment]
I've tested this addon (I was thinking about doing a new one, but I found this), and it fails at getting a song list. I've the latest google api you're using installed in my linux system. It doesn't seem to be a google api failure, i think that's a parsing problem from your script, if I have some time I'll try to fix it.

Anyway, great add-on! :D

**Comment by ghost** [comment]
I think I've found the problem, there's some trouble with a sql command in GoogleMusicStorage.py at method _clearPlaylist (line 154). I don't know how's the database implemented, I'm trying to understand it but commenting from line 154 to line 157 it works (the database wont clear but at least the plugin is working).

**Comment by gvdhoven** [comment]
Same problem here.

p.s. i changed the default.py script based on this error.

removed: 
    if (not settings.getSetting("firstrun")):
        storage.initializeDatabase()
        settings.setSetting("firstrun", "1")

changed _init_ method from GoogleMusicStorage.py:
    def **init**(self):
        self.xbmc = sys.modules["**main**"].xbmc
        self.xbmcvfs = sys.modules["**main**"].xbmcvfs
        self.settings = sys.modules["**main**"].settings
        self.path = os.path.join(self.xbmc.translatePath("special://database"), self.settings.getSetting('sqlite_db'))

```
    if (not os.path.isfile(self.path)):
        self.initializeDatabase()
```

So database gets initialized if you forecebly remove it.

**Comment by gvdhoven** [comment]
Update: I've forked and did some more work on my branch, i will send a pull request when i'm finished.

**Comment by dcdevito** [comment]
can anyone tell me how to retrieve (any) logs from Raspbmc? I was able to install it and get it to run through some smaller playlists, however it works on some playlists but fails for most and also fails when loading all songs.

I wish I could help - I'm a developer so if there's any code to update and/or test let me know.

Cheers

**Comment by anshul10s** [comment]
Should be at usual location, your home folder/. xbmc/logs

**Comment by vially** [comment]
This should be fixed in the develop branch. If it still doesn't work feel free to reopen.
