### ISSUE TITLE
Error import descriptor_pb2 don't found.

### ISSUE THREAD

**Issue by antoine-morisseau** [vially/googlemusic-xbmc#30]
Hello i followed your tuto.
i installed the mutagen first then gmusicapi and finally the add on.

i'm using the two step authentication on my google account but used the 
application specific password : 
after restarted the xbmc app the log gave me this error :

20:37:11 T:3036  NOTICE: -->Python Interpreter Initialized<--
20:37:12 T:4684  NOTICE: Thread Jobworker start, auto delete: true
20:37:16 T:1928  NOTICE: Thread Background Loader start, auto delete: false
20:37:19 T:3888  NOTICE: Previous line repeats 1 times.
20:37:19 T:3888  NOTICE: Thread XBPyThread start, auto delete: false
20:37:19 T:3888  NOTICE: -->Python Interpreter Initialized<--
20:37:19 T:3888  NOTICE: GoogleMusic-0.8.2 ARGV: ['plugin://plugin.audio.googlemusic/', '1', '']
20:37:19 T:3888   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: cannot import name descriptor_pb2
                                            Traceback (most recent call last):
                                              File "C:\Users\Keizo\AppData\Roaming\XBMC\addons\plugin.audio.googlemusic\default.py", line 43, in <module>
                                                import GoogleMusicApi
                                              File "C:\Users\Keizo\AppData\Roaming\XBMC\addons\plugin.audio.googlemusic\GoogleMusicApi.py", line 3, in <module>
                                                from gmusicapi.api import Api
                                              File "C:\Users\Keizo\AppData\Roaming\XBMC\addons\script.module.gmusicapi\lib\gmusicapi__init__.py", line 10, in <module>
                                                from gmusicapi.api import Api
                                              File "C:\Users\Keizo\AppData\Roaming\XBMC\addons\script.module.gmusicapi\lib\gmusicapi\api.py", line 22, in <module>
                                                from gmusicapi.protocol import webclient, musicmanager, upload_pb2, locker_pb2
                                              File "C:\Users\Keizo\AppData\Roaming\XBMC\addons\script.module.gmusicapi\lib\gmusicapi\protocol\musicmanager.py", line 16, in <module>
                                                from gmusicapi.protocol import upload_pb2, locker_pb2
                                              File "C:\Users\Keizo\AppData\Roaming\XBMC\addons\script.module.gmusicapi\lib\gmusicapi\protocol\upload_pb2.py", line 6, in <module>
                                                from google.protobuf import descriptor_pb2
                                            ImportError: cannot import name descriptor_pb2
                                            -->End of Python script error report<--
20:37:19 T:4112   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.audio.googlemusic/
20:37:19 T:4112   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.audio.googlemusic/) failed

I'm using windows 7 and the last version of xbmc Frodo 12.2

Kind regards.

**Comment by mikesalmonuk** [comment]
I'm getting the same problem - any idea of a fix?

**Comment by vially** [comment]
I think you're using a different version of the gmusicapi addon than the one mentioned in the mentioned in the thread.
Can you install the one from the thread and post the log here again?

**Comment by mikesalmonuk** [comment]
I followed the instructions, installed the dependant modules, and then get this error:

http://pastebin.com/qpkfn8xr

**Comment by mikesalmonuk** [comment]
Sorry, that was a previous install. The latest error I got was:

http://pastebin.com/StmDMgXg

**Comment by vially** [comment]
Apparently you're not using the version posted by me in the forum. You're using a slightly different version posted by @foreverguest (which should be better than mine but last time I checked the dependencies in his version are packaged in a slightly different way).

Can you try with the version posted in the first post of the thread and see if you get the same error?

**Comment by mikesalmonuk** [comment]
OK, just uninstalled and re-installed with the latest "develop" branch. Got the following errors:

http://pastebin.com/SzAW8pUu

"Error Contents: cannot import name Mobileclient"

**Comment by vially** [comment]
The `develop` branch requires the latest version of the `gmusicapi` while you have an older version installed. 

In order to get this addon to work you have to make sure you have already installed the right versions of it's dependencies (e.g.: gmusicapi) for which it was built.

One way to do this would be to install exactly the versions mentioned in this [forum post](http://forum.xbmc.org/showthread.php?tid=134783&pid=1134966) which were tested to be compatible.

If you want to install a newer version (e.g.: the develop branch) then you'll also need to find proper versions for it's dependencies and install them in the right order which might be a lot of work.

Anyway, I'm in the process of rewriting this addon from scratch and when I'm done the installation process should be much easier, but I'm not sure when this new version will be available so I wouldn't hold my breath.

**Comment by mikesalmonuk** [comment]
Thanks for the update. It seems to have been a bit more successful, but getting another error now.

Contents: type object 'GetLibrarySongs' has no attribute 'get_auth'

http://pastebin.com/pN8KyCLA

I have two factor auth on my account, and used my username and auth'd password in the config.

Thanks.

**Comment by vially** [comment]
The cause of this error is not obvious to me and I don't have enough time to dig deeper into it right now. Your best bet  would be to either look through the forum posts and try to get a newer version to install and work (e.g.: GoogleMusic-0.8exp14) or wait until we'll release the next version.

**Comment by mikesalmonuk** [comment]
Where could I find the download link to GoogleMusic-0.8exp14 or is that what's available in the main page here?

**Comment by vially** [comment]
You can get it from [here](http://forum.xbmc.org/showthread.php?tid=134783&pid=1542471#pid1542471)

**Comment by mikesalmonuk** [comment]
Thanks! Just tried, and seemed to progress a but further than before, but now having a Python error with an int() function - 

http://pastebin.com/zXJCyS74

**Comment by foreverguest** [comment]
Try to clean your cache and cookies.

**Comment by mikesalmonuk** [comment]
Hi - it works now perfectly. Thanks. I simply installed GoogleMusic-0.8exp14 from https://app.box.com/s/5u5601atbrnmf991ynp0 , cleared my cache and cookies and worked 100% as expected. Thanks again!
