### ISSUE TITLE
Error import

### ISSUE THREAD

**Issue by unthoiz** [vially/googlemusic-xbmc#31]
11:53:26 T:2757751872  NOTICE: -->Python Interpreter Initialized<--
11:53:26 T:2757751872   DEBUG: Process - The source file to load is /home/pi/.xbmc/addons/plugin.audio.googlemusic/default.py
11:53:27 T:2757751872   DEBUG: Process - Setting the Python path to /home/pi/.xbmc/addons/plugin.audio.googlemusic:/opt/xbmc-bcm/xbmc-bin/share/xbmc/addons/script.module.pil/lib:/opt/xbmc-bcm/xbmc-bin/share/xbmc/addons/script.module.pysqlite/lib:/home/pi/.xbmc/addons/script.module.simplejson/lib:/home/pi/.xbmc/addons/script.common.plugin.cache/lib:/home/pi/.xbmc/addons/script.module.mutagen/lib:/home/pi/.xbmc/addons/script.module.gmusicapi/lib:/usr/lib/python2.7:/usr/lib/python2.7/plat-linux2:/usr/lib/python2.7/lib-tk:/usr/lib/python2.7/lib-old:/usr/lib/python2.7/lib-dynload:/usr/local/lib/python2.7/dist-packages:/usr/lib/python2.7/dist-packages:
11:53:27 T:2757751872   DEBUG: Process - Entering source directory /home/pi/.xbmc/addons/plugin.audio.googlemusic
11:53:27 T:2757751872   DEBUG: Instantiating addon using automatically obtained id of "plugin.audio.googlemusic" dependent on version 2.1.0 of the xbmc.python api
11:53:27 T:2757751872  NOTICE: GoogleMusic-0.8.2 ARGV: ['plugin://plugin.audio.googlemusic/', '1', '']
11:53:27 T:3041014400   DEBUG: ------ Window Init (DialogBusy.xml) ------
11:53:29 T:2757751872   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named requests
                                            Traceback (most recent call last):
                                              File "/home/pi/.xbmc/addons/plugin.audio.googlemusic/default.py", line 43, in <module>
                                                import GoogleMusicApi
                                              File "/home/pi/.xbmc/addons/plugin.audio.googlemusic/GoogleMusicApi.py", line 3, in <module>
                                                from gmusicapi.api import Api
                                              File "/home/pi/.xbmc/addons/script.module.gmusicapi/lib/gmusicapi/**init**.py", line 10, in <module>
                                                from gmusicapi.api import Api
                                              File "/home/pi/.xbmc/addons/script.module.gmusicapi/lib/gmusicapi/api.py", line 15, in <module>
                                                import requests
                                            ImportError: No module named requests
                                            -->End of Python script error report<--
11:53:29 T:3041014400   DEBUG: ------ Window Init (DialogKaiToast.xml) ------
11:53:29 T:2757751872    INFO: Python script stopped
11:53:29 T:2757751872   DEBUG: Thread XBPyThread 2757751872 terminating
11:53:29 T:2792354880   DEBUG:  WaitOnScriptResult - plugin exited prematurely - terminating
11:53:29 T:3041014400   ERROR: GetDirectory - Error getting plugin://plugin.audio.googlemusic/
11:53:29 T:3041014400   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.audio.googlemusic/) failed
11:53:29 T:3041014400   DEBUG: CGUIMediaWindow::GetDirectory (addons://sources/audio/)

**Comment by foreverguest** [comment]
the requests module was not installed
