### ISSUE TITLE
Long playback gap between songs

### ISSUE THREAD

**Issue by worldspawn** [vially/googlemusic-xbmc#39]
Hey, i'm running this on raspbmc and internet throughput is about 10Mb. Firstly, thanks! Having google music on my new pi is truly awesome :smil

There are long gaps between playing songs on playlists (i've only tried playlist thus far). I get the loading animation between songs but only after about 15 or so seconds of watching the visualizer flatline and nothing happening. The gap isn't epic but its certainly too long to run a house party on. About 25 or so seconds. Perhaps the plugin could get the next song before the current once finishes?

**Comment by foreverguest** [comment]
Hi, I use the add-on on a pi too, but I have about 2 seconds delay between songs, and my Internet is only 5Mb.
You can enable the option 'Pre-fetch Url' in the add-on settings, it can save a couple of seconds.
Other options you can try to decrease the gap: decreasing the buffering on xbmc, using xbmc gotham, overcloking your pi and disabling other services in the pi that could be using cpu/net resources.
