### ISSUE TITLE
googlemusic will not login

### ISSUE THREAD

**Issue by ghost** [vially/googlemusic-xbmc#40]
Hi. I installed the latest Latest development release - version 0.8exp19 (3 zip files) from here: http://forum.xbmc.org/showthread.php?tid=134783&pid=1134966#pid1134966

When I open the add-on it hangs trying to login.

Here's the debug log:
http://xbmclogs.com/show.php?id=188755

Any chance you can take a look?

Much appreciated  :)

**Comment by foreverguest** [comment]
Please test with version from post #444 on the forum thread. Just 1 zip file needed.
