### ISSUE TITLE
Why vendor in gmusicapi?

### ISSUE THREAD

**Issue by denibertovic** [vially/googlemusic-xbmc#44]
Can't we use use the release that's on pypi? Or git submodules perhaps?

**Comment by foreverguest** [comment]
I chose to include a simplified version of the gmusicapi because the complete version does much more than is needed and requires a lot more dependencies.
These dependencies can make the addon slower. On my primary platform, a raspberry pi, it made a big difference.

**Comment by denibertovic** [comment]
How can dependencies make the addon slower if this functionality isn't used (ie. if you only use a subset of the gmusicapi?)

**Comment by denibertovic** [comment]
My primary platform is a rpi as well btw.

**Comment by foreverguest** [comment]
When you do a 'import' usually the called modules do some initializations/verifications even if you don't use it.

**Comment by denibertovic** [comment]
I'm am aware of this...But imports having side effects is a very bad practice.... What I'm saying is that the proper way would be to fix these things in the upstream library instead of vendoring in a small subset.

**Comment by razzeee** [comment]
it should probably also be a module. like these:

https://github.com/beenje/script.module.requests
https://github.com/Eldorados/script.module.urlresolver
https://github.com/Razzeee/script.module.trakt

**Comment by foreverguest** [comment]
gmusicapi removed.
