### ISSUE TITLE
Albums not loading tracks.

### ISSUE THREAD

**Issue by dexdeadly** [vially/googlemusic-xbmc#46]
Here is the error:

22:31:20 T:2528130128  NOTICE: -->Python Interpreter Initialized<--
22:31:20 T:2528130128  NOTICE: GoogleMusicEXP-1.2 ARGV: ['plugin://plugin.audio.googlemusic.exp/', '23', '?path=search_result&query=Abominationz%20(Monoxide)%20Twiztid']
22:31:24 T:2528130128  NOTICE: [GoogleMusicEXP-1.2] Loading auth from cache
22:31:26 T:2528130128   ERROR: /storage/.xbmc/addons/script.module.requests/lib/requests/packages/urllib3/connectionpool.py:730: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html (This warning will only appear once by default.)
                                              InsecureRequestWarning)
22:31:26 T:2561684560  NOTICE: Thread BackgroundLoader start, auto delete: false

**Comment by dexdeadly** [comment]
More information, I'm getting this on Gotham build of OpenElec

**Comment by foreverguest** [comment]
This should be fixed, reopen if needed.
