### ISSUE TITLE
Library Update Errors

### ISSUE THREAD

**Issue by xtrem007** [vially/googlemusic-xbmc#49]
11:53:05 T:804769792  NOTICE: Starting Kodi (14.1 Git:2015-01-30-38e4046-dirty). Platform: iOS ATV2 ARM (Thumb) 32-bit
11:53:05 T:804769792  NOTICE: Using Release Kodi x32 build (version for AppleTV2)
11:53:05 T:804769792  NOTICE: Kodi compiled Jan 30 2015 by GCC 4.2.1 for iOS ATV2 ARM (Thumb) 32-bit version 4.2.0 (40200)
11:53:05 T:804769792  NOTICE: Running on Apple Inc. AppleTV2,1 with iOS 6.1.4, kernel: Darwin ARM 32-bit version 13.0.0

11:53:17 T:158396416  NOTICE: -->Python Interpreter Initialized<--
11:53:17 T:158396416  NOTICE: GoogleMusicEXP-1.3 ARGV: ['plugin://plugin.audio.googlemusic.exp/', '1', '']
11:53:20 T:158396416  NOTICE: [GoogleMusicEXP-1.3] Loading auth from cache
11:53:20 T:137777152  NOTICE: Thread BackgroundLoader start, auto delete: false
11:53:27 T:158396416  NOTICE: Thread LanguageInvoker start, auto delete: false
11:53:27 T:158396416  NOTICE: -->Python Interpreter Initialized<--
11:53:27 T:158396416  NOTICE: GoogleMusicEXP-1.3 ARGV: ['plugin://plugin.audio.googlemusic.exp/', '-1', '?action=update_library']
11:53:29 T:158396416  NOTICE: [GoogleMusicEXP-1.3] Loading auth from cache
11:53:29 T:168783872  NOTICE: Thread LanguageInvoker start, auto delete: false
11:53:30 T:168783872  NOTICE: -->Python Interpreter Initialized<--
11:53:30 T:168783872  NOTICE: GoogleMusicEXP-1.3 ARGV: ['plugin://plugin.audio.googlemusic.exp/', '-1', '']
11:53:32 T:168783872  NOTICE: [GoogleMusicEXP-1.3] Trying to fetch the device_id
11:53:32 T:168783872  NOTICE: [GoogleMusicEXP-1.3] Logging in
11:53:44 T:168783872  NOTICE: [GoogleMusicEXP-1.3] ConnectionError(ReadTimeoutError("HTTPSConnectionPool(host='play.google.com', port=443): Read timed out.",),)
11:53:44 T:168783872  NOTICE: [GoogleMusicEXP-1.3] Login succeeded
11:53:44 T:168783872   ERROR: /var/mobile/Library/Preferences/Kodi/addons/script.module.requests/lib/requests/packages/urllib3/connectionpool.py:730: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html (This warning will only appear once by default.)
                                              InsecureRequestWarning)
11:53:54 T:168783872  NOTICE: [GoogleMusicEXP-1.3] No device found, using default.
11:53:54 T:168783872  NOTICE: [GoogleMusicEXP-1.3] Found device_id: 333c60412227c96f
11:53:54 T:168783872  NOTICE: [GoogleMusicEXP-1.3] Loading library
11:53:54 T:168783872  NOTICE: [GoogleMusicEXP-1.3] Loading auth from cache
11:54:12 T:168783872  NOTICE: [GoogleMusicEXP-1.3] Library Size: 1402
11:54:14 T:168783872 WARNING: Attempt to use invalid handle -1
11:54:14 T:168783872   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: an integer is required
                                            Traceback (most recent call last):
                                              File "/var/mobile/Library/Preferences/Kodi/addons/plugin.audio.googlemusic.exp/default.py", line 79, in <module>
                                                navigation.listMenu()
                                              File "/var/mobile/Library/Preferences/Kodi/addons/plugin.audio.googlemusic.exp/GoogleMusicNavigation.py", line 92, in listMenu
                                                self.xbmcplugin.addSortMethod(handle1, self.xbmcplugin.SORT_METHOD_UNSORTED)
                                            TypeError: an integer is required
                                            -->End of Python script error report<--

**Comment by foreverguest** [comment]
Bug confirmed. I'm working to release a new version soon, the fix will be included there.

**Comment by foreverguest** [comment]
Please confirm if it works in this version:
https://app.box.com/s/d0h56sddqomwj46f8amipcebjikpf2w5

**Comment by Fredjames** [comment]
I Can't Login at all I keep getting the same pop up 
![google kodi issue](https://cloud.githubusercontent.com/assets/12139782/7352032/e9f7c446-ecbd-11e4-87b0-e79eb5cd40a5.PNG)

**Comment by foreverguest** [comment]
Have you tried enabling less secure apps in your Google account (https://www.google.com/settings/security/lesssecureapps)?

**Comment by Fredjames** [comment]
thanks now I can login now but I get a new error that it can't play song 
and I have the new on 1,4

**Comment by foreverguest** [comment]
Check if you have at least one mobile device and total less than 10 devices registered: https://play.google.com/music/listen#/settings

**Comment by Fredjames** [comment]
I did I have 4 mobile Device but I see it not only google play but all my stuff can't load
