### ISSUE TITLE
Password is stored in plaintext in settings file.

### ISSUE THREAD

**Issue by AndrejG82** [vially/googlemusic-xbmc#50]
I noticed that plugin stores the password in plaintext in settings.xml file. Is there any way to avoid that?

**Comment by foreverguest** [comment]
Maybe we can encode before storing, but it will be something simple.

**Comment by AndrejG82** [comment]
Would it be possible to use something like OAuth to avoid storing password altogether?

**Comment by foreverguest** [comment]
It would be great, but I lack the knowledge to implement this and even in the Unofficial-Google-Music-API project people have tried and failed to implement it.

**Comment by foreverguest** [comment]
OAuth implemented, please test:
https://app.box.com/s/kc2irpnjwvt1z33ut6t6o3qyi5p7dy1c

**Comment by razzeee** [comment]
Hrm, better. But the password is still there even if it's base64 encoded. Not really oauth or am I wrong?

**Comment by foreverguest** [comment]
Password is still required by the method implemented in gmusicapi. Please follow discussion in this thread: https://github.com/simon-weber/gmusicapi/issues/168
