### ISSUE TITLE
Error opening addon on openelec on Raspberry Pi 1

### ISSUE THREAD

**Issue by buggzy1011** [vially/googlemusic-xbmc#58]
Every time I try to open Google Play Music on openelec, running on a Raspberry Pi 1 model B, it gives me a script failed message.

**Comment by foreverguest** [comment]
Have you checked the log for errors?

**Comment by debian-professional** [comment]
I found the reason of this error. This occurs only on startup if you have to load the Music into the Database (create a new one). If you do copy the database and the correct settings xml file from a other computer running with this addon to the RaspberryPi, the Addon will work like a charm. I do later send a log file.  

How to fix the addon with RaspberryPi look here 

http://forum.kodi.tv/showthread.php?tid=200640&page=36

**Comment by foreverguest** [comment]
Are you willing to do some tests for me? I have an idea to fix this.

**Comment by debian-professional** [comment]
Hello Leonardo
Yes, of course. I could do some test for you. But it is only guess.
You need a log of the  crashed System ?
In the momemt I do connect to my RaspberryPi over SMB or SSH and do delete
the Database manually, the hole system freezes and the only thing to do is
remove power to reboot. I had this kind of crash anytime I forced the
RaspberryPi to build a new Database.
I could try to freeze the System during I would enable Full Debug
Informstion and to get the log File from the SD Card in a other Computer.
If only the Addon itself would crash it would be a easy part to get the
logs but this error freezes the hole system into a unuseable state and
after the crash only icmp replys to the RasperryPi do still work.
With reagrds from switzerland
Hans
Am 29.10.2015 01:04 schrieb "Leonardo Cervo" notifications@github.com:

**Comment by foreverguest** [comment]
My guess is that a large song library is using too much memory to load in the database, so I'm preparing a version that will load small chunks of the library.

**Comment by debian-professional** [comment]
Yes. My collection is huge. I have over 27 0000 songs inside my google
music  account.
Am 29.10.2015 14:06 schrieb "Leonardo Cervo" notifications@github.com:

**Comment by debian-professional** [comment]
The crashed database has allwas a size of 11MB. The stable Database from my
Notebook has a size of 20 MB.
Am 29.10.2015 14:11 schrieb "Hans Weber" linuxluemmel.ch@gmail.com:

**Comment by foreverguest** [comment]
Please try version in link below:
https://app.box.com/s/yg74fh17jq093l5tzfegxgz7jq58mazh

**Comment by debian-professional** [comment]
Perfect. It works
Best regards from switzerland
Hans

2015-10-30 19:54 GMT+01:00 Leonardo Cervo notifications@github.com:

**Comment by foreverguest** [comment]
This should be fixed in latest version:
https://app.box.com/s/o4fyik63cnqw47jr2cnsuaf2tdy37fu8
