### ISSUE TITLE
Fix sharing from Yatse

### ISSUE THREAD

**Issue by ffleischer** [vially/googlemusic-xbmc#61]
The line 
`get = params.get`
is missing in GoogleMusicActions::playAll, which results in an error when trying to share an album from Yatse (XBMC remote)

**Comment by kylegordon** [comment]
This appears to have been fixed in the latest rev, in https://github.com/vially/googlemusic-xbmc/blob/develop/GoogleMusicActions.py

**Comment by ffleischer** [comment]
Awesome :+1:
