### ISSUE TITLE
Error creating kodi favorites (on sub menus)

### ISSUE THREAD

**Issue by iam-william** [vially/googlemusic-xbmc#63]
version 1.4alpha3 on kodi Amazon Fire TV
Error (Script failed! : Google  Music EXP) when trying to add a favourite on the Library sub menus (example: "Albums").  Doesn't add it to Kodi Favourites.

However,  favourite-ing still functions on the first menu item "Google Music EXP"

---

Prior version sub menu favourite-ing worked (1.2 or 1.3?)

**Comment by foreverguest** [comment]
Bug confirmed, thanks.

**Comment by foreverguest** [comment]
Fix committed to develop branch.
