### ISSUE TITLE
Possible to fill Player.GetItem fanart attributes so can be used?

### ISSUE THREAD

**Issue by Ghawken** [vially/googlemusic-xbmc#65]
Hi
Thanks for plugin.
Notice that the fanart attribute from AudioGetItem, or Player.GetItem appears to always be blank?
eg.
http://127.0.0.1:8181/jsonrpc?request={"jsonrpc": "2.0", "method": "Player.GetItem", "params": { "properties": ["title", "album", "artist", "duration", "thumbnail", "file", "fanart", "streamdetails"], "playerid": 0 }, "id": "AudioGetItem"}

result:
{"id":"AudioGetItem","jsonrpc":"2.0","result":{"item":{"album":"","artist":["Cassidy"],"duration":0,"fanart":"","file":"https://r4---sn-ppoxu-ntqe.c.doc-0-0-sj.sj.googleusercontent.com/videoplayback?id===

Can this be updated to point to fanart so that it can be used on web pages/secondary remotes?

**Comment by foreverguest** [comment]
I don't know how. 
Could you point me to an addon where this attribute is filled?

**Comment by Ghawken** [comment]
Believe was JSON Kodi error - that these were empty.
Kodi Trak indicates fixed 13 days ago - yet to test

**Comment by foreverguest** [comment]
Closing, please reopen if you find any info on this
