### ISSUE TITLE
Add an album to queue

### ISSUE THREAD

**Issue by mruwek** [vially/googlemusic-xbmc#72]
I know that there is "Play all" option on albums, but it clears current queue and fills it with tracks from that album. What I propose is this: don't touch tracks that are already present on queue and add tracks from selected album **after** them. Adding every single track of an album manually is just painful.

**Comment by mruwek** [comment]
![screenshot-gpm](https://cloud.githubusercontent.com/assets/500710/10217967/afa5ee02-6833-11e5-989d-25e64fb07ac8.png)

**Comment by mruwek** [comment]
Here it is on Google Play Music itself:

![screenshot-gpm](https://cloud.githubusercontent.com/assets/500710/10217967/afa5ee02-6833-11e5-989d-25e64fb07ac8.png)

**Comment by foreverguest** [comment]
I'll try to add this option.

**Comment by foreverguest** [comment]
This was added in last version:
https://app.box.com/s/o4fyik63cnqw47jr2cnsuaf2tdy37fu8
