### ISSUE TITLE
Genre only shows titltes instead of albums

### ISSUE THREAD

**Issue by debian-professional** [vially/googlemusic-xbmc#74]
I work with last public version of this addon. Version 1.5 
Inside the the section "genre" it shows only titles instead of albums.

**Comment by foreverguest** [comment]
I'll try to fix this for next version, thanks.

**Comment by foreverguest** [comment]
This is fixed in last version:
https://app.box.com/s/o4fyik63cnqw47jr2cnsuaf2tdy37fu8
