### ISSUE TITLE
Play of the Music over the categorie (added in the last release) is not working 

### ISSUE THREAD

**Issue by debian-professional** [vially/googlemusic-xbmc#80]
If I do open the categorys over the addon I get a empty list.

**Comment by foreverguest** [comment]
Bug confirmed, I'll look into it ASAP.

**Comment by foreverguest** [comment]
Please check if version below fix the issue:
https://app.box.com/s/agcyvtnvfo4r38kj58ce4ddc2oshzer6

**Comment by debian-professional** [comment]
Works fine with one little exception. The Album Art inside the categrory is
completly diffrend than inside the Google Music App.

2015-11-29 3:12 GMT+01:00 Leonardo Cervo notifications@github.com:

**Comment by debian-professional** [comment]
![2016-01-05 09_46_12-genres - google play musik](https://cloud.githubusercontent.com/assets/15184091/12110921/519713f0-b391-11e5-9b79-595813b3f4da.png)
![2016-01-05 09_46_42-meine musik - google play musik](https://cloud.githubusercontent.com/assets/15184091/12110920/51959ffc-b391-11e5-941a-7111225c2521.png)

It seems Google uses the first 5 Albums inside a category to bild the picture for a category. 
Would it be possible to use the same trick to build a category picture ? 
So it would look like the native Google Play Music Application ?

**Comment by foreverguest** [comment]
I believe this is done in the browser via javascript. I don't know a easy way to that in the addon with python.
