### ISSUE TITLE
does not play any songs

### ISSUE THREAD

**Issue by akorinek** [vially/googlemusic-xbmc#82]
Hi,

I've installed the plugin and can login. However I cannot get it to play any tracks. I click on "I'm feeling lucky mix" and get only an empty playlist. This is the error I get in the logfile:

11:07:18 T:2922411072  NOTICE: [GoogleMusicEXP-1.6] **\* NO TRACKS **\* CallFailure('400 Client Error: Bad Request for url: https://mclients.googleapis.com/sj/v2.0w/radio/stationfeed?alt=json&include-tracks=true\n(requests kwargs: {\'url\': \'https://mclients.googleapis.com/sj/v2.0w/radio/stationfeed\', \'headers\': {\'Content-Type\': \'application/json\', \'Authorization\': \'<omitted>\'}, \'data\': \'{"contentFilter": 1, "stations": [{"numEntries": 100, "recentlyPlayed": [], "radioId": "IFL"}]}\', \'method\': \'POST\', \'params\': {\'alt\': \'json\', \'include-tracks\': \'true\'}})\n(response was: \'{\n "error": {\n  "errors": [\n   {\n    "domain": "global",\n    "reason": "badRequest",\n    "message": "Bad Request"\n   }\n  ],\n  "code": 400,\n  "message": "Bad Request"\n }\n}\n\')',)

**Comment by 123THOR567** [comment]
I have the same issue on a fresh install in Kodibuntu (from the repository).  I can browse and see customized playlists based on things I've listened to from other devices, but when I open any playlist, it shows me an empty list with zero items.

**Comment by foreverguest** [comment]
Do you have uploaded songs?

**Comment by akorinek** [comment]
No, I'm new to google music, just want to use it as a replacement for songza, where I stream songs.

**Comment by foreverguest** [comment]
Please test version below, free radio should work:
https://app.box.com/s/rsoenjmj3uub12v9g5mpxor99xn7lwn9

**Comment by foreverguest** [comment]
Free radios should be w working now.
https://app.box.com/s/bf8447r2c5574gwjtiaj469awatpebus

**Comment by akorinek** [comment]
Working now, sorry about the delay in reporting, needed to install newer version on my Amlogic box
