### ISSUE TITLE
Playlist not fully showing 

### ISSUE THREAD

**Issue by Q-efx** [vially/googlemusic-xbmc#83]
When I create a Playlist on my phone from an album of and later add other songs it only shows the items from the first added album and not any new items. 

Steps:
Add play list from album
Update on kodi. Playlist shows all songs. 
Add a new song to playlist
Update Playlist on kodi. 
Still old playlist

**Comment by foreverguest** [comment]
Please try updating the library.

**Comment by foreverguest** [comment]
Closing, reopen if still a issue.
