### ISSUE TITLE
Can't add album or song to music library

### ISSUE THREAD

**Issue by altmenorg** [vially/googlemusic-xbmc#89]
Hi ;)

Everything went fine until 1.8.3 came in and since then I get the following issue :+1: 
02:20:25 T:140014350882560  NOTICE: Thread LanguageInvoker start, auto delete: false
02:20:25 T:140014350882560  NOTICE: -->Python Interpreter Initialized<--
02:20:25 T:140014350882560  NOTICE: [GoogleMusicEXP-1.8.3]  ARGV: ['plugin://plugin.audio.googlemusic.exp/', '-1', '?action=add_album_library&album_id=Bpzdke6xwp4f5mrejq4xl7toyu4']
02:20:25 T:140014350882560  NOTICE: [GoogleMusicEXP-1.8.3] Loading auth from cache
02:20:26 T:140014350882560  NOTICE: [GoogleMusicEXP-1.8.3] Loaded 15 tracks (1 art miss)
02:20:26 T:140014350882560   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: (0,)
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.audio.googlemusic.exp/default.py", line 18, in <module>
                                                GoogleMusicActions.GoogleMusicActions().executeAction(action, params)
                                              File "/storage/.kodi/addons/plugin.audio.googlemusic.exp/GoogleMusicActions.py", line 34, in executeAction
                                                self.api.addAAtrack(track[0])
                                            KeyError: (0,)
                                            -->End of Python script error report<--

I hope this helps !

**Comment by foreverguest** [comment]
Thanks it helped.
Please check if version below fixes the error:
https://app.box.com/s/ywvsfr3dyv30ng4srbf23x3d196gaj4v

**Comment by foreverguest** [comment]
Fixed
