### ISSUE TITLE
Unable to play songs

### ISSUE THREAD

**Issue by coreybruce** [vially/googlemusic-xbmc#94]
I am unable to play my music as I get a Google Music EXP error and playback failed error

**Comment by foreverguest** [comment]
If you can browse but fails when trying to play, probably you don't have an Android device registered in your account.

**Comment by coreybruce** [comment]
I do have a Android device registered which is my nexus 5
http://i.imgur.com/IQvJuat.png

Of course this has nothing to do with the issues which worked on earlier versions

**Comment by foreverguest** [comment]
Ok, could you please upload your log with errors to pastebin so I can have a look.

**Comment by coreybruce** [comment]
How do I get the error log on kodi?

**Comment by foreverguest** [comment]
http://kodi.wiki/view/Log_file

**Comment by coreybruce** [comment]
Well Paste Bin didn't like me pasting my log file in so I uploaded and shared my whole log file on my Google Drive
https://drive.google.com/file/d/0B2S_72oCP_4XeHR2eGNwYmxyTGs/view?usp=sharing

**Comment by foreverguest** [comment]
Thanks, your error is:
"LookupError: no codec search functions registered: can't find encoding"
This is a common error with OpenElec, I don't know why but a encoding module is missing.
Try another OpenElec version or if you have recently upgraded your version try to downgrade.

**Comment by coreybruce** [comment]
hmm that sucks, this use to work on open elec on my Raspberry Pi which use to work fine, I'm going to test it on OSMC another one based on kodi for raspberry pi and see if it works. I will get back to you if it works or not.

**Comment by coreybruce** [comment]
Ok it works on OSMC which is good so confirmed there is a missing dependency that needs to be addressed.
